apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  namespace: homework
spec:
  replicas: 3
  selector:
    matchLabels:
      app: server
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: server
    spec:
      nodeSelector:
        homework: "true"
      initContainers:
      - name: init-page
        image: busybox@sha256:ab33eacc8251e3807b85bb6dba570e4698c3998eca6f0fc2ccb60575a563ea74
        command: ['sh', '-c', 'wget https://pikabu.ru -O /init/index.html']
        volumeMounts:
        - name: homework-volume
          mountPath: /init
      containers:
      - name: nginx-container
        image: nginx@sha256:42a516af16b852e33b7682d5ef8acbd5d13fe08fecadc7ed98605ba5e3b26ab8
        ports:
        - containerPort: 8000
        lifecycle:
          preStop:
            exec:
              command: ['sh', '-c', 'rm', '/homework/index.html']
        volumeMounts:
        - name: homework-volume
          mountPath: /homework
        - name: config
          mountPath: /etc/nginx/conf.d
          readOnly: true
        readinessProbe:
          exec:
            command:
            - cat
            - /homework/index.html
          initialDelaySeconds: 1
          periodSeconds: 5
      volumes:
      - name: homework-volume
        emptyDir: {}
      - name: config
        configMap:
          name: nginx-config
          items:
          - key: default.conf
            path: default.conf
