apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: server
  namespace: homework
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: custom-storage-class
  resources:
    requests:
      storage: 100Mi
